services:
  - type: web
    name: telegram-bot-web
    env: python
    buildCommand: ""
    startCommand: ""
    plan: free
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python bot.py"
    plan: free
